# Rubocop Config

AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'lib/modules/minizinc/yarpler_output/*'
    - 'lib/yarpl/*'

Metrics/LineLength:
  Max: 120

Style/CaseIndentation:
  Enabled: false