module Yarpler
  module Utils
    class Minizinc

      T_CONSTANT = "%s: %s = %s;\n" # int: id_dienst_frei = 0;
      T_INCLUDES = "include \"globals.mzn\";\n"
      T_HEADER = "%% File generated by YARPLER\n"
      T_OUTPUT = ", \"%s=\" , show(%s) , \" \"   "
      T_VARIABLE = "var %s: %s;\n" # var 0..2: m0t0;
      T_FOOTER = "solve satisfy;" # @TODO: Wird momentan als Hack missbraucht um den kompletten Durchstich zu ermöglichen ;)

      def run_from_file(filename)
        file = File.new(filename, "r")
        content = file.read
        file.close
        run(content)
      end

      def run(model)
        path = 'wrk.mzn'
        File.open(path, "wb") { |f| f.write(model) }
        @cmd = %x( minizinc #{path} )
      end

      def convert(d)
        @output="output [ \"\" "
        code = T_HEADER
        code << T_INCLUDES
        d.each do |key, var|
          var.get_list_of_attributes
          code<<convert_attributes(key, var)
        end
        code << @output + "];\n"
        code << T_FOOTER
        code
      end

      def convert_attributes(name, ressource, reference = false)
        code=""
        ressource.get_list_of_attributes.each do |a|
          case ressource.get_variabletype(a)
            when "CONSTANT"
              if reference
                next
              end
              code<< T_CONSTANT % [ressource.get_datatype(a), a + "_" + name, ressource.load(a)]
            when "VARIABLE"
              if !reference && ressource.is_referenced
                next
              end
              code<< T_VARIABLE % [ressource.load(a), name + "_" + a]
              @output << T_OUTPUT % [name + "_" + a,name + "_" + a]
            when "REFERENCE"
              ressource.get_value(a).each do |r|
                code << convert_attributes(name.to_s+"_"+r.get_instance_name().to_s, r, true )
              end
          end
        end
        code
      end

      def print
        puts @cmd
      end

    end
  end
end