module Yarpler
  # The Interpreter is responsible for interpreting the AST generated by ANTLR3
  # It builds the Interface to all the Yarpler::Interpreters
  class Interpreter

    # Initialize an interpreter
    def initialize
    end

    # Interprets an AST from ANTLR
    #
    # @param antlr_ast [ANTLR3::AST::CommonTree] interpreted problem as an ANTLR AST
    # @return [Problem] interpreted yarpl problem
    def interpret(antlr_ast)
      antlr_ast.each do |item|
        interpret_block(item)
      end
      Yarpler::Models::Problem.instance
    end

    # Interprets the main blocks of the YARPL file
    #
    # @param item [ANTLR3::AST::CommonTree] ANTLR token, first level of a yarpl problem
    #   MODEL_DECLARATION, INITIAL_DECLARATION or SOLVE_DECLARATION
    # @return [void]
    def interpret_block(item)
      case item.to_s
      when 'MODEL_DECLARATION'
        interpret_model_declaration(item)
      when 'INITIAL_DECLARATION'
        interpret_initial_declaration(item)
      when 'SOLVE_DECLARATION'
        interpret_solve_declaration(item)
      else
        Yarpler::Log.instance.warn 'Block could not be interpreted'
      end
    end

    # Interprets a model declaration
    #
    # @param item [ANTLR3::AST::CommonTree] model node to interpret
    # @return [void]
    def interpret_model_declaration(item)
      Yarpler::Interpreters::ModelInterpreter.new(item)
    end

    # Interprets an initial declaration
    #
    # @param item [ANTLR3::AST::CommonTree] initial node to interpret
    # @return [void]
    def interpret_initial_declaration(item)
      initial = Yarpler::Interpreters::InitialInterpreter.new(item)
      Yarpler::Models::Problem.instance.objects = initial.objects
    end

    # Interprets a solve declaration
    #
    # @param item [ANTLR3::AST::CommonTree] solve node to interpret
    # @return [void]
    def interpret_solve_declaration(item)
      solve_interpreter = Yarpler::Interpreters::SolveInterpreter.new(item, Yarpler::Models::Problem.instance.objects)
      Yarpler::Models::Problem.instance.solve = solve_interpreter.solve
      Yarpler::Models::Problem.instance.constraints = solve_interpreter.constraints
    end
  end
end
